### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by dasanchez** [hyphacoop/cosmos-ansible#168]
- [ ] Chain agnostic approach
  - [X] node role: #129 
  - [ ] Chain selection mechanism
- [ ] Gaia v8.0.0 support
- [ ] Multi-node setup:  #20 
- [ ] Relayer support
  - [ ] Hermes v1.0.0
- [ ] Key Management System support
  - [ ] Hardware
- [ ] Consensus monitor: #125 
- [ ] Block explorer role: #124 
- [ ] Simply VC PANIC support
- [ ] Node control
  - [ ] Upgrade operation: #134 
- [ ] Guided inventory setup: #95 
- [ ] Interchain Security testing support
